
// Objective-C API for talking to the following Go packages
//
//	github.com/sonr-io/sonr/bind/motor-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Motor_FRAMEWORK_H__
#define __Motor_FRAMEWORK_H__

#include "SNRMotor.objc.h"
#include "Universe.objc.h"

#endif
